# Generated by Django 5.1 on 2024-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.TextField(default='user')),
                ('profile_image', models.TextField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('social_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
