# Generated by Django 5.1 on 2024-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mission',
            table='Mission',
        ),
        migrations.AlterModelTable(
            name='mission_user_mapping',
            table='Mission_User_mapping',
        ),
    ]
